name: CI
on: [pull_request, push]
jobs:
  test_and_build:
    name: Test and Build
    container: node:13
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Clean install dependencies
        run: npm ci
        working-directory: ./theme

      - name: Test
        run: npm test
        working-directory: ./theme

      - name: Build and zip
        run: |
          npm run build
          apt-get update && apt-get install zip
          npm run zip
        working-directory: ./theme